{% set version = "1.2.11" %}

package:
    name: zlib
    version: {{ version }}

source:
    url: http://zlib.net/zlib-{{ version }}.tar.gz
    sha256: c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1

build:
    number: 0
    run_exports:
        - {{ pin_subpackage('zlib', max_pin='x.x') }}

test:
    commands:
        - test -f ${PREFIX}/lib/libz.a  # [unix]

about:
    home: http://zlib.net/
    license: zlib
    summary: Massively spiffy yet delicately unobtrusive compression library
    license_family: Other
    description: |
      zlib is designed to be a free, general-purpose, lossless data-compression
      library for use on virtually any computer hardware and operating system.
    doc_url: http://zlib.net/manual.html
    dev_url: https://github.com/madler/zlib
