{% set version = "2020.6.24" %}

package:
  name: ca-certificates
  version: {{ version }}

source:
  # updates and sha256 published at: https://curl.haxx.se/docs/caextract.html
  fn: cacert.pem
  url: https://curl.haxx.se/ca/cacert-2020-06-24.pem
  sha256: 726889705b00f736200ed7999f7a50021b8735d53228d679c4e6665aa3b44987

build:
  number: 0
  commands:
    # Verify the certificates are there.
    - test -f "${PREFIX}/ssl/cacert.pem"                                      # [unix]
    - test -f "${PREFIX}/ssl/cert.pem"                                        # [unix]
    - if not exist %LIBRARY_PREFIX%\\ssl\\cacert.pem exit 1                   # [win]
    - if not exist %LIBRARY_PREFIX%\\ssl\\cert.pem exit 1                     # [win]

    # Use the certificates to download something.
    - /usr/bin/openssl -CAfile "${PREFIX}/ssl/cacert.pem" -CApath nosuchdir s_client -showcerts -connect www.google.com:443  # [unix]

    - /usr/bin/curl --cacert "${PREFIX}/ssl/cacert.pem" https://www.google.com         # [unix]
    - /usr/bin/curl --cacert %LIBRARY_PREFIX%\\ssl\\cacert.pem https://www.google.com  # [win]

about:
  home: https://github.com/conda-forge/ca-certificates-feedstock
  license: MPL 2.0
  license_file: LICENSE.txt
  summary: Certificates for use with other packages.

extra:
  recipe-maintainers:
     - jakirkham
     - jjhelmus
     - msarahan
     - mwcraig
     - ocefpaf
     - patricksnape
     - pelson
     - scopatz
